#!/usr/bin/env node
/**
 * scripts/apply-seo.ts
 *
 * Reads every `entry.json` sidecar and injects the manifest's metadata as
 * SEO tags into the HTML document that entry's `href` points at. One
 * standardized facet set per entry: canonical URL, description, OpenGraph,
 * Twitter card, and a JSON-LD blob.
 *
 *   npx tsx scripts/apply-seo.ts
 *   npx tsx scripts/apply-seo.ts --base=https://games.cognotik.com
 *   npx tsx scripts/apply-seo.ts --check      # CI: fail on drift
 *
 * Everything is written inside a managed region:
 *
 *   <!-- manifest:seo:start (generated by scripts/apply-seo.ts — do not edit) -->
 *   …
 *   <!-- manifest:seo:end -->
 *
 * Markup outside those markers is never touched, so hand-authored <head>
 * content survives. Re-running replaces the region in place, which makes
 * the script idempotent and safe to wire into a build.
 *
 * Flags:
 *   --root=<path>     repository root (default: parent of scripts/)
 *   --base=<url>      site origin used for canonical/OG urls
 *                     (default: https://games.cognotik.com)
 *   --image=<path>    fallback social image (default: /assets/og-image.png)
 *   --site-name=<s>   og:site_name (default: Mathematical Explorations)
 *   --twitter=<@user> twitter:site handle (optional)
 *   --only=<a,b,c>    restrict to these entry ids
 *   --force-title     rewrite an existing <title> to the manifest title
 *   --strip           remove the managed region instead of writing it
 *   --dry-run         print what would change, touch nothing
 *   --check           write nothing; exit 1 if any file would change
 *   --quiet           only print the summary
 *   --help            print this banner
 */

import {promises as fs} from 'node:fs';
import path from 'node:path';
import process from 'node:process';
import {fileURLToPath} from 'node:url';

import {
    type Category,
    ENTRY_FILENAME,
    type EntryFile,
    isExternal,
    joinPosix,
    resolvePathRef,
    splitPathSuffix,
    validateEntryFile,
} from './manifest_schema.ts';

/* ---------------------------------------------------------------- args */

const argv = process.argv.slice(2);
const flag = (name: string) => argv.includes(`--${name}`);
const opt = (name: string, fallback: string) => {
    const prefix = `--${name}=`;
    const hit = argv.find((a) => a.startsWith(prefix));
    return hit ? hit.slice(prefix.length) : fallback;
};
const listOpt = (name: string): string[] | null => {
    const raw = opt(name, '\u0000');
    if (raw === '\u0000') return null;
    return raw.split(',').map((s) => s.trim()).filter(Boolean);
};

if (flag('help')) {
    console.log(
        [
            'usage: apply-seo [--base=<url>] [--image=<path>] [--site-name=<s>]',
            '                 [--twitter=@handle] [--only=id,id] [--force-title]',
            '                 [--strip] [--dry-run] [--check] [--quiet]',
            '',
            'Injects manifest metadata as SEO tags into each entry\'s target HTML.',
        ].join('\n'),
    );
    process.exit(0);
}

const HERE = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(opt('root', path.join(HERE, '..')));
const BASE = opt('base', 'https://games.cognotik.com').replace(/\/+$/, '');
const IMAGE = opt('image', '/assets/og-image.png');
const SITE_NAME = opt('site-name', 'Mathematical Explorations');
const TWITTER = opt('twitter', '');
const ONLY = listOpt('only');
const FORCE_TITLE = flag('force-title');
const STRIP = flag('strip');
const DRY_RUN = flag('dry-run');
const CHECK = flag('check');
const QUIET = flag('quiet');

const log = (...a: unknown[]) => {
    if (!QUIET) console.log(...a);
};

const START = '<!-- manifest:seo:start (generated by scripts/apply-seo.ts — do not edit) -->';
const END = '<!-- manifest:seo:end -->';
/** Tolerant of an older/edited opening marker comment. */
const REGION = /[ \t]*<!--\s*manifest:seo:start[\s\S]*?manifest:seo:end\s*-->[ \t]*\r?\n?/i;

/* --------------------------------------------------------------- walk */

const IGNORED_DIRS = new Set([
    'node_modules', '.git', '.idea', 'dist', 'build', 'out', 'target',
    'vendor', 'coverage', '__pycache__', 'venv', 'site-packages',
]);

async function* findEntryFiles(relDir = '', depth = 0): AsyncGenerator<string> {
    if (depth > 6) return;
    let dirents;
    try {
        dirents = await fs.readdir(path.join(ROOT, relDir), {withFileTypes: true});
    } catch {
        return;
    }
    for (const d of dirents) {
        if (d.name.startsWith('.') && d.name !== ENTRY_FILENAME) continue;
        const rel = relDir ? joinPosix(relDir, d.name) : d.name;
        if (d.isDirectory()) {
            if (IGNORED_DIRS.has(d.name)) continue;
            yield* findEntryFiles(rel, depth + 1);
        } else if (d.isFile() && d.name === ENTRY_FILENAME) {
            yield rel;
        }
    }
}

/* ------------------------------------------------------------ rendering */

function escapeAttr(value: string): string {
    return value
        .replace(/&/g, '&amp;')
        .replace(/</g, '&lt;')
        .replace(/>/g, '&gt;')
        .replace(/"/g, '&quot;');
}

/** `</script>` inside JSON-LD would close the block early. */
function escapeJsonLd(value: string): string {
    return JSON.stringify(value, null, 2).replace(/</g, '\\u003c');
}

/** Turn a pitch (which may carry inline HTML) into plain prose. */
function toPlainText(html: string): string {
    return html
        .replace(/<[^>]*>/g, ' ')
        .replace(/&nbsp;/gi, ' ')
        .replace(/&amp;/gi, '&')
        .replace(/&lt;/gi, '<')
        .replace(/&gt;/gi, '>')
        .replace(/&quot;/gi, '"')
        .replace(/&#39;/gi, "'")
        .replace(/\s+/g, ' ')
        .trim();
}

/** Search snippets get cut near 160 chars; cut on a word boundary. */
function truncate(text: string, max = 200): string {
    if (text.length <= max) return text;
    const cut = text.slice(0, max);
    const space = cut.lastIndexOf(' ');
    return `${(space > max * 0.6 ? cut.slice(0, space) : cut).trimEnd()}…`;
}

function absoluteUrl(rootRelative: string): string {
    if (isExternal(rootRelative)) return rootRelative;
    return `${BASE}/${rootRelative.replace(/^\/+/, '')}`;
}

const SCHEMA_TYPE: Record<Category, string> = {
    lab: 'WebApplication',
    game: 'VideoGame',
    essay: 'Article',
};

interface Facets {
    title: string;
    description: string;
    canonical: string;
    image: string;
    video: string;
    keywords: string[];
    category: Category;
}

function facetsFor(entry: EntryFile, dir: string, hrefRel: string): Facets {
    const description = truncate(
        toPlainText(entry.subtitle ?? '') || toPlainText(entry.pitch ?? '') || entry.title,
    );
    const video = entry.video && !isExternal(entry.video)
        ? absoluteUrl(splitPathSuffix(resolvePathRef(dir, entry.video))[0])
        : (entry.video ?? '');
    return {
        title: entry.title,
        description,
        canonical: absoluteUrl(hrefRel),
        image: absoluteUrl(IMAGE),
        video,
        keywords: entry.tags ?? [],
        category: entry.category,
    };
}

function renderRegion(f: Facets, indent: string): string {
    const tags: string[] = [];
    const meta = (attr: 'name' | 'property', key: string, value: string) => {
        if (value) tags.push(`<meta ${attr}="${key}" content="${escapeAttr(value)}" />`);
    };

    tags.push(`<link rel="canonical" href="${escapeAttr(f.canonical)}" />`);
    meta('name', 'description', f.description);
    if (f.keywords.length) meta('name', 'keywords', f.keywords.join(', '));

    meta('property', 'og:type', f.category === 'essay' ? 'article' : 'website');
    meta('property', 'og:site_name', SITE_NAME);
    meta('property', 'og:title', f.title);
    meta('property', 'og:description', f.description);
    meta('property', 'og:url', f.canonical);
    meta('property', 'og:image', f.image);
    if (f.video) meta('property', 'og:video', f.video);

    meta('name', 'twitter:card', 'summary_large_image');
    if (TWITTER) meta('name', 'twitter:site', TWITTER);
    meta('name', 'twitter:title', f.title);
    meta('name', 'twitter:description', f.description);
    meta('name', 'twitter:image', f.image);

    const jsonLd: Record<string, unknown> = {
        '@context': 'https://schema.org',
        '@type': SCHEMA_TYPE[f.category],
        name: f.title,
        headline: f.title,
        description: f.description,
        url: f.canonical,
        image: f.image,
        isPartOf: {'@type': 'WebSite', name: SITE_NAME, url: BASE},
    };
    if (f.keywords.length) jsonLd.keywords = f.keywords.join(', ');
    // Article wants `headline`; everything else wants `name`. Drop the noise.
    if (f.category !== 'essay') delete jsonLd.headline;
    else delete jsonLd.name;

    const body = tags.map((t) => `${indent}${t}`).join('\n');
    const ld =
        `${indent}<script type="application/ld+json">\n` +
        `${escapeJsonLd(jsonLd as unknown as string).split('\n').map((l) => indent + l).join('\n')}\n` +
        `${indent}</script>`;

    return `${indent}${START}\n${body}\n${ld}\n${indent}${END}\n`;
}

/* --------------------------------------------------------------- patch */

/** Insert/replace the managed region; returns the new document. */
function patchHtml(html: string, region: string, title: string): string {
    let out = html;

    if (REGION.test(out)) {
        out = out.replace(REGION, region);
    } else if (STRIP) {
        return out;
    } else {
        const headClose = /<\/head\s*>/i.exec(out);
        if (headClose) {
            out = out.slice(0, headClose.index) + region + out.slice(headClose.index);
        } else {
            // No <head>: fall back to just after <html> or the very top.
            const htmlOpen = /<html[^>]*>\s*/i.exec(out);
            const at = htmlOpen ? htmlOpen.index + htmlOpen[0].length : 0;
            out = out.slice(0, at) + region + out.slice(at);
        }
    }

    if (!STRIP) {
        const hasTitle = /<title[^>]*>[\s\S]*?<\/title>/i.test(out);
        if (!hasTitle) {
            out = out.replace(REGION, (m) => `${m}`); // no-op, keeps types simple
            const anchor = out.indexOf(START);
            const line = `<title>${escapeAttr(title)}</title>\n`;
            const indent = /(^|\n)([ \t]*)$/.exec(out.slice(0, anchor))?.[2] ?? '';
            out = out.slice(0, anchor) + line + indent + out.slice(anchor);
        } else if (FORCE_TITLE) {
            out = out.replace(
                /<title[^>]*>[\s\S]*?<\/title>/i,
                `<title>${escapeAttr(title)}</title>`,
            );
        }
    }
    return out;
}

/* ---------------------------------------------------------------- main */

async function main(): Promise<void> {
    const warnings: string[] = [];
    let written = 0;
    let unchanged = 0;
    let skipped = 0;
    let drift = false;

    const sources: string[] = [];
    for await (const rel of findEntryFiles()) sources.push(rel);
    sources.sort();
    log(`  scan     ${sources.length} ${ENTRY_FILENAME} file(s)`);

    for (const source of sources) {
        let raw: unknown;
        try {
            raw = JSON.parse(await fs.readFile(path.join(ROOT, source), 'utf8'));
        } catch (err) {
            warnings.push(`${source}: invalid JSON — ${(err as Error).message}`);
            skipped++;
            continue;
        }
        const problems = validateEntryFile(raw, source);
        if (problems.length) {
            warnings.push(...problems);
            skipped++;
            continue;
        }
        const entry = raw as EntryFile;
        if (ONLY && !ONLY.includes(entry.id)) continue;
        if (entry.hidden) {
            log(`  hidden   ${source}`);
            continue;
        }

        const dir = path.posix.dirname(source);
        if (isExternal(entry.href)) {
            log(`  external ${source}`);
            continue;
        }
        const [hrefRel] = splitPathSuffix(resolvePathRef(dir, entry.href));
        if (!/\.x?html?$/i.test(hrefRel)) {
            warnings.push(`${source}: href "${hrefRel}" is not an HTML document — skipped`);
            skipped++;
            continue;
        }

        const absolute = path.resolve(ROOT, hrefRel);
        if (!absolute.startsWith(ROOT + path.sep)) {
            warnings.push(`${source}: refusing to write outside root: ${hrefRel}`);
            skipped++;
            continue;
        }
        const html = await fs.readFile(absolute, 'utf8').catch(() => null);
        if (html === null) {
            warnings.push(`${source}: target "${hrefRel}" does not exist — skipped`);
            skipped++;
            continue;
        }

        const facets = facetsFor(entry, dir, hrefRel);
        const indent = /\n([ \t]+)<\/head\s*>/i.exec(html)?.[1] ?? '  ';
        const patched = patchHtml(html, STRIP ? '' : renderRegion(facets, indent), facets.title);

        if (patched === html) {
            unchanged++;
            log(`  ok       ${hrefRel}`);
            continue;
        }
        drift = true;
        if (CHECK) {
            console.error(`  DRIFT    ${hrefRel}`);
            continue;
        }
        if (DRY_RUN) {
            written++;
            log(`  ${STRIP ? 'strip ' : 'update'}   ${hrefRel} (dry run)`);
            continue;
        }
        await fs.writeFile(absolute, patched, 'utf8');
        written++;
        log(`  ${STRIP ? 'strip ' : 'update'}   ${hrefRel}`);
    }

    if (warnings.length) {
        console.warn('\nwarnings:');
        for (const w of warnings) console.warn(`  ! ${w}`);
    }
    console.log(
        `\napply-seo: ${written} updated, ${unchanged} unchanged, ${skipped} skipped` +
        `${DRY_RUN ? ' (dry run)' : ''} @ ${BASE}`,
    );
    if (CHECK && drift) {
        console.error('apply-seo --check: HTML is stale, re-run without --check');
        process.exitCode = 1;
    }
}

main().catch((err) => {
    console.error(`apply-seo failed: ${(err as Error).message}`);
    process.exitCode = 1;
});