#!/usr/bin/env node
// Measures the analytic model against the reference solver over a grid of (h/R, tilt)
// and fits the gap-term fade (plan R7) from the reference's own gap cancellation.
// Usage: node tools/fit.js [--write]
import fs from 'node:fs';
import { fileURLToPath } from 'node:url';
import * as V from '../src/core/vec3.js';
import { createUniformGravity } from '../src/core/background.js';
import { makePortal } from '../src/core/portal.js';
import { createPair } from '../src/core/portalMap.js';
import { createAnalyticModel } from '../src/core/field/analytic.js';
import { solveReferencePairs } from '../src/core/field/reference.js';
import { samplePoints, relativeRmsError, distanceToDisk } from '../src/core/field/compare.js';
import { createRng } from '../src/core/rng.js';
import COEF from '../src/core/field/coefficients.js';

const bg = createUniformGravity({ g: 9.81 });
const R = 1;
const write = process.argv.includes('--write');

function pairFor(h, tiltDeg) {
  const t = (tiltDeg * Math.PI) / 180;
  const a = makePortal({ id: 1, center: [0, 0, 0], normal: [0, 1, 0], up: [0, 0, -1], radius: R, linkId: 2 });
  const b = makePortal({ id: 2, center: [0, h, 0], normal: [Math.sin(t), -Math.cos(t), 0], radius: R, linkId: 1 });
  return createPair(a, b, bg);
}

const rows = [];
for (const h of [0.5, 1, 2, 3, 4, 6]) {
  for (const tilt of [0, 45]) {
    const pair = pairFor(h, tilt);
    const ref = solveReferencePairs([pair], bg, { rings: 14, sectors: 24 });
    const model = createAnalyticModel([pair], { terms: { gap: false } });
    const mid = V.lerp(pair.a.center, pair.b.center, 0.5);
    const pts = samplePoints(createRng(5), mid, 3 * R, 250,
      (p) => distanceToDisk(pair.a, p) > 0.1 * R && distanceToDisk(pair.b, p) > 0.1 * R);
    const rms = relativeRmsError(model.field, ref.field, pts);
    const cancel = V.dot(ref.field(mid), bg.up) / bg.g;
    rows.push({ h, tilt, rms, cancel });
    console.log(`h/R=${h}\ttilt=${tilt}\trms(physical)=${rms.toFixed(3)}\tref gap cancellation=${cancel.toFixed(3)}`);
  }
}

function crossing(level) {
  const co = rows.filter((r) => r.tilt === 0);
  for (let i = 1; i < co.length; i++) {
    const a = co[i - 1], b = co[i];
    if ((a.cancel - level) * (b.cancel - level) <= 0 && a.cancel !== b.cancel) {
      return a.h + ((level - a.cancel) * (b.h - a.h)) / (b.cancel - a.cancel);
    }
  }
  return null;
}

const lo = crossing(0.8), hi = crossing(0.3);
console.log(`suggested gapFadeLo≈${lo ?? 'n/a'} gapFadeHi≈${hi ?? 'n/a'} (current ${COEF.gapFadeLo}/${COEF.gapFadeHi})`);

if (write && lo != null && hi != null && hi > lo) {
  const out = fileURLToPath(new URL('../src/core/field/coefficients.js', import.meta.url));
  const next = { ...COEF, gapFadeLo: +lo.toFixed(3), gapFadeHi: +hi.toFixed(3) };
  const body = Object.entries(next).map(([k, v]) => `  ${k}: ${v},`).join('\n');
  fs.writeFileSync(out, `// Generated by tools/fit.js. Edit design knobs by hand, re-run to refit.\nexport default Object.freeze({\n${body}\n});\n`);
  console.log(`wrote ${out}`);
}